### ISSUE TITLE
Change tooltip template

### ISSUE THREAD

**Issue by kamov** [Thrilleratplay/jquery-validation-bootstrap-tooltip#21]
Hi,
I need to change style of tooltip only for this error handle.
bootstrap tooltip offer way to customize template, using option:

```js
$().tooltip({
  template: '<div class="tooltip CUSTOM-CLASS"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
})
```

But how to do this on your plugin?
thanks!

**Comment by Thrilleratplay** [comment]
There are two ways.  Either setting the message value through jQuery Validation or setting the title value through Bootstrap.  Here is a fiddle with both examples: https://jsfiddle.net/thrilleratplay/8cgj5c3u/

Just be sure to enable the 'html' option in Bootstrap's Tooltip to render the HTML instead of displaying as a string.

**Comment by kamov** [comment]
Thank you!

**Comment by kamov** [comment]
It's possible to enable html for all fields?
Something like:
tooltip_options: {
                html: true
            }
Thanks

**Comment by Thrilleratplay** [comment]
Yes.  Using the '_all_' parameter.  Example: https://jsfiddle.net/thrilleratplay/8cgj5c3u/8/

**Comment by kamov** [comment]
Thank You for your awesome support.
