### ISSUE TITLE
Not support chosen

### ISSUE THREAD

**Issue by jast90** [Thrilleratplay/jquery-validation-bootstrap-tooltip#30]
Not support [chosen]( https://harvesthq.github.io/chosen/)

**Comment by jast90** [comment]
https://github.com/Thrilleratplay/jquery-validation-bootstrap-tooltip/issues/14

**Comment by jast90** [comment]
http://jsfiddle.net/jast90/1260d6em/4/ the tooltips position is not correct ! If i [addClassRules](https://jqueryvalidation.org/jQuery.validator.addClassRules/) the position is not in correct.

**Comment by jast90** [comment]
[bootstrap doc](http://getbootstrap.com/javascript/#tooltips-usage) 
> Don't try to show tooltips on hidden elements
> Invoking $(...).tooltip('show') when the target element is display: none; will cause the tooltip to be incorrectly positioned.

**Comment by Thrilleratplay** [comment]
I see.  I'm sorry, due to the number of additional jQuery plugins and versions that could possibly create conflicts, this project can not support all of the permutations.  My suggestion is to fork this project and make the modifications you need.  I have very limited free time in the near future so unfortunately I cannot provide much help beyond that.

**Comment by jast90** [comment]
Thank you all the same.
