### ISSUE TITLE
Tooltip is not removing when field is hidden

### ISSUE THREAD

**Issue by MohammadMasood** [Thrilleratplay/jquery-validation-bootstrap-tooltip#34]
![screenshot from 2017-04-29 12 48 06](https://cloud.githubusercontent.com/assets/15152669/25553808/ebaa2518-2cda-11e7-8414-74c8976c2569.png)

**Comment by Thrilleratplay** [comment]
It looks like if a "Payment Method" option is selected a "bank name" and "cheque number" field will appear.  However, if the user tries to submit without filling out those fields and reselects the "Select Payment Method" option, the fields will hide but the tooltip will remain.  If this is correct, the issue is that form validation has not reset.  First I would make "Select Payment Method" the default but a [nonselectable disabled option](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option).  Second, try to revalidate the form for the onChange event for the select element if it has been submitted before.

if the user has not changed "Select Payment Method" and clicks submit resulting in tooltips appearing like that, I would ask for a jsFiddle example as there could be a few things going on.  In more recent versions of jQuery Validation (after v1.10 if I remember correctly), the [validation method will ignore hidden input fields](https://jqueryvalidation.org/validate/) but I don't believe this works that same way if a parent element like a DIV is controlling the visibility.

**Comment by MohammadMasood** [comment]
Thanks  for the help , 
I read jquery validation's example as you referred and used depends parameter and its working now ,thanks again.
Here is the solution I used : 
Example: Specifies a contact element as required and as email address, the latter depending on a checkbox being checked for contact via email.

$("#myform").validate({
  rules: {
    contact: {
      required: true,
      email: {
        depends: function(element) {
          return $("#contactform_email").is(":checked");
        }
      }
    }
  }
});
