### ISSUE TITLE
there is conflict in jquery-ui and this library

### ISSUE THREAD

**Issue by iPazooki** [Thrilleratplay/jquery-validation-bootstrap-tooltip#41]
if you use both jquery-ui and this plugin, you will get this error message:

**cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'**

is there any workaround?

**Comment by Thrilleratplay** [comment]
The issue is not with this plugin, it is because jQuery-UI and Bootstrap both have tooltip functionality.  You can [try this](https://stackoverflow.com/questions/13731400/jqueryui-tooltips-are-competing-with-twitter-bootstrap/19247955#19247955) but your issue is outside of the scope of this project.

**Comment by iPazooki** [comment]
I tried what you said, but it was useless. so it seems there is no way for using this library with jQuery-UI and Bootstrap.

Thanks anyway.

**Comment by Thrilleratplay** [comment]
Sorry @iPazooki.  If possible try using a customized bundle jQuery-UI without the tooltip component.
